const size = {
  GalaxyFold: "280px",
  mobileS: "320px",
  mobileM: "375px",
  mobileL: "425px",
  surfaceDuo: "540px",
  smallTablet: "680px",
  ipadMini: "768px",
  tablet: "820px",
  BreakPoint: "850px",
  SurfacePro7: "912px",
  NestHub: "1024px",
  laptop: "1366px",
  laptopL: "1440px",
  desktop: "2560px",
};

export const device = {
  GalaxyFold: `(max-width: ${size.GalaxyFold})`,
  mobileS: `(max-width: ${size.mobileS})`,
  mobileM: `(max-width: ${size.mobileM})`,
  mobileL: `(max-width: ${size.mobileL})`,
  surfaceDuo: `(max-width: ${size.surfaceDuo})`,
  smallTablet: `(max-width: ${size.smallTablet})`,
  ipadMini: `(max-width: ${size.ipadMini})`,
  BreakPoint: `(max-width: ${size.BreakPoint})`,
  tablet: `(max-width: ${size.tablet})`,
  SurfacePro7: `(max-width: ${size.SurfacePro7})`,
  NestHub: `(max-width: ${size.NestHub})`,
  laptop: `(max-width: ${size.laptop})`,
  laptopL: `(max-width: ${size.laptopL})`,
  desktop: `(max-width: ${size.desktop})`,
};
